# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Goyoke < Formula
  desc "Programmatic enforcement for Claude Code agentic workflows"
  homepage "https://github.com/Bucket-Chemist/goYoke"
  version "0.5.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Bucket-Chemist/goYoke/releases/download/v0.5.5/goYoke_0.5.5_darwin_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "d29484a37dd0b5a7ed854cd4ed940566f674efb14192d95d5a93ef50c5a73eb2"

      define_method(:install) do
        bin.install "goyoke"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Bucket-Chemist/goYoke/releases/download/v0.5.5/goYoke_0.5.5_darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "1b3e875b446e91db33c993591ca6e60a37185c5b4b7789c9733c1b4ce04669ac"

      define_method(:install) do
        bin.install "goyoke"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Bucket-Chemist/goYoke/releases/download/v0.5.5/goYoke_0.5.5_linux_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "e47952668de8a653b916e2c4d1ae0d5a91534ea0a5115a2c4c0be787d6979093"
      define_method(:install) do
        bin.install "goyoke"
      end
    end
  end

  test do
    system bin/"goyoke", "version"
  end
end
