# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Goyoke < Formula
  desc "Programmatic enforcement for Claude Code agentic workflows"
  homepage "https://github.com/Bucket-Chemist/goYoke"
  version "0.5.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Bucket-Chemist/goYoke/releases/download/v0.5.3/goYoke_0.5.3_darwin_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "d9aa35d49c860c04309aad7a937b9bcb77b6c466736e447be7a390312d73a41d"

      define_method(:install) do
        bin.install "goyoke"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Bucket-Chemist/goYoke/releases/download/v0.5.3/goYoke_0.5.3_darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "afebb27208c1b78894f81408e506b532dde2382f7531124f7228509af420e8a9"

      define_method(:install) do
        bin.install "goyoke"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Bucket-Chemist/goYoke/releases/download/v0.5.3/goYoke_0.5.3_linux_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "0015b409fe4bdc5aa9645df2cf947b0fedc57ff1fbe5f78370afd237bc053235"
      define_method(:install) do
        bin.install "goyoke"
      end
    end
  end

  test do
    system bin/"goyoke", "version"
  end
end
