# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Goyoke < Formula
  desc "Programmatic enforcement for Claude Code agentic workflows"
  homepage "https://github.com/Bucket-Chemist/goYoke"
  version "0.5.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Bucket-Chemist/goYoke/releases/download/v0.5.2/goYoke_0.5.2_darwin_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "aef7f7196043b38d25fff3d2498e9b98453d52a29e93408696c2903f44450c03"

      define_method(:install) do
        bin.install "goyoke"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Bucket-Chemist/goYoke/releases/download/v0.5.2/goYoke_0.5.2_darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "d951dcf0b10b267ba5ce0f2d5d5b4a4a9f466ebb1ea1951664b664ca5698ab3c"

      define_method(:install) do
        bin.install "goyoke"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Bucket-Chemist/goYoke/releases/download/v0.5.2/goYoke_0.5.2_linux_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "ac83e3393a509c318f3a4ba133d030d28b731cae5aad6d82d6ae3ed99c8cf00d"
      define_method(:install) do
        bin.install "goyoke"
      end
    end
  end

  test do
    system bin/"goyoke", "version"
  end
end
