# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoyokeDev < Formula
  desc "Programmatic enforcement for Claude Code agentic workflows"
  homepage "https://github.com/Bucket-Chemist/goYoke"
  version "0.5.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Bucket-Chemist/goYoke-dev/releases/download/v0.5.1/goYoke_0.5.1_darwin_amd64.tar.gz"
      sha256 "a93b6f9440314f84fa11d84710345583a0ecad279a7dac946adc363d5958a74b"

      define_method(:install) do
        bin.install "goyoke"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Bucket-Chemist/goYoke-dev/releases/download/v0.5.1/goYoke_0.5.1_darwin_arm64.tar.gz"
      sha256 "894c0a3ad05ab7ee2f34d4cfb554826583dee0d50adadc824199d6f002c71d3f"

      define_method(:install) do
        bin.install "goyoke"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Bucket-Chemist/goYoke-dev/releases/download/v0.5.1/goYoke_0.5.1_linux_amd64.tar.gz"
      sha256 "b7bd5adcf4ec861e9dda6a14d6d30d60e1719db32329b144c14c5abdcd9bd236"
      define_method(:install) do
        bin.install "goyoke"
      end
    end
  end

  test do
    system bin/"goyoke", "version"
  end
end
